- hosts: "{{ servers }}"
  gather_facts: false
  name: "Installs node_exporter"
  tasks:
    - name: Download and extract the latest release from GitHub (prometheus/node_exporter)
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
    - name: Create a node_exporter user
      user:
        name: node_exporter
        comment: node_exporter
        groups: node_exporter
        shell: /bin/false
        createhome: yes
        home: /home/node_exporter