---
name: Lint Code Base
on:
  push:
    branches-ignore:
      - "master"
jobs:
  build:
    name: GitHub Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_MD: true
          VALIDATE_ANSIBLE: true
          ANSIBLE_DIRECTORY: /ansible-forge
          VALIDATE_YAML: true
          VALIDATE_PYTHON: true
          VALIDATE_POWERSHELL: true
